CREATE DATABASE IF NOT EXISTS web_ii;
USE web_ii;

CREATE TABLE IF NOT EXISTS alunos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    matricula VARCHAR(30) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    dataNasc DATE NOT NULL,
    email VARCHAR(160) NOT NULL
);

CREATE TABLE IF NOT EXISTS professores (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    matricula VARCHAR(30) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    dataNasc DATE NOT NULL,
    email VARCHAR(160) NOT NULL
);
